"""
Django settings for almokhbir project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from celery.schedules import crontab
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i8%dky-f&ykm+c-$q-da-5r^tg$!i+v_9wn07)5jf8d%id$y5#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'news_manager',
    'telegram_bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'almokhbir.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'almokhbir.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/home/saad/projects/almokhbir/static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6399/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6399/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Casablanca'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'fetch-and-send-news-morning': {
        'task': 'news_manager.tasks.fetch_and_send_news',
        'schedule': crontab(hour=8, minute=0),
        'options': {'timezone': 'Africa/Casablanca'},
    },
    'fetch-and-send-news-evening': {
        'task': 'news_manager.tasks.fetch_and_send_news',
        'schedule': crontab(hour=20, minute=00),
        'options': {'timezone': 'Africa/Casablanca'},
    },
}

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, '/home/saad/projects/almokhbir/static')]
# PayPal API credentials
PAYPAL_CLIENT_ID = 'AUz1mcLVNM0DFEdgEogWNmsCaz1UPtNBgVkknn-2iD6fXezgE9jrVCor7qGHxP_92jKyQBXOFvC_BQz7'
PAYPAL_CLIENT_SECRET = 'EOYqvjNf3uAyQBhw9sQt-7nriePwNdn8hAV4S52ZszP8rLNnc-YdI8eVE_I7LoIoZyzgozF6Jkx89064'
PAYPAL_API_BASE = 'https://api-m.sandbox.paypal.com'  # Use 'https://api-m.paypal.com' for live
PAYPAL_MODE = 'sandbox'


